resolver: lts-13.17
packages:
- .
extra-deps:
- http2-client-0.9.0.0
- http2-client-grpc-0.7.0.0
- http2-grpc-types-0.4.0.0
- lens-labels-0.2.0.1
- proto-lens-0.5.0.0
- proto-lens-runtime-0.5.0.0
- proto-lens-protoc-0.5.0.0
flags: {}
extra-package-dbs: []
